### PR TITLE
video: handle ending calls.

### PR DESCRIPTION
**Pull request by Pranav2612000**

### CODE REVIEW

**Comment by veddandekar** [comment]
There seems to be an issue with this fix. If the end call button is pressed when no call is in progress, the entire page seems to crash.
Could you add a check to prevent the same?

On a side note, button seems to get stuck after closing the call. I will work on fixing that along with #3 after this is merged.

**Comment by Pranav2612000** [comment]
> There seems to be an issue with this fix. If the end call button is pressed when no call is in progress, the entire page seems to crash.
> Could you add a check to prevent the same?
> 
> On a side note, button seems to get stuck after closing the call. I will work on fixing that along with #3 after this is merged.

Cant reproduce

**Comment by veddandekar** [comment]
Screenshot from 2020-05-18 20-36-46

**Comment by Pranav2612000** [comment]
Still cant reproduce. 

But seeing the error, adding a premature exit if `this.state.myMediaObject` doesn't exist should solve the problem.

**Comment by Pranav2612000** [comment]
Fixed.

**Pull request merged**
